[package]
name = "stabble"
version = "0.1.0"
edition = "2021"

[dependencies]
idls-common = { path = "../common" }
substreams = { workspace = true }
substreams-solana = { workspace = true }
solana-program = { workspace = true }
borsh = { workspace = true }

